name: test-action

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Install vCert CLI and test presence in path
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Install vCert CLI
        uses: ./
      - name: Check install
        run: vcert -version
      - name: Check root directory
        shell: bash
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'should be clean'
            exit 1
          else
            exit 0
          fi
  custom:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Install vCert CLI and test presence in path
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Install vCert CLI
        uses: ./
        with:
          release: 'v5.11.1'
      - name: Check install
        run: vcert -version
      - name: Check root directory
        shell: bash
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'should be clean'
            exit 1
          else
            exit 0
          fi

  wrong_version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Try to install a wrong version
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Install vCert CLI
        uses: ./
        with:
          release: honk
        continue-on-error: true

  custom_dir:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Install vCert CLI and test presence in path
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Install vCert CLI
        uses: ./
        with:
          install-dir: "$HOME/.vcerttest"
      - name: Check install
        run: vcert -version
      - name: Check install dir
        shell: bash
        run: |
          [[ $(dirname "$(which vcert)") == "$HOME/.vcerttest" ]]
      - name: Check root directory
        shell: bash
        run: |
          [[ -z $(git diff --stat) ]]

  custom_dir_root:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    permissions: {}
    name: Install vCert CLI and test presence in path with custom root dir
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Install vCert CLI
        uses: ./
        with:
          install-dir: /usr/bin
          use-sudo: true
      - name: Check install
        run: vcert -version
      - name: Check install dir
        shell: bash
        run: |
          [[ $(dirname "$(which vcert)") == /usr/bin ]]
      - name: Check root directory
        shell: bash
        run: |
          [[ -z $(git diff --stat) ]]

  required:
    needs:
    - default
    - custom
    - wrong_version
    - custom_dir
    - custom_dir_root
    runs-on: ubuntu-latest
    steps:
    - run: echo "Required jobs success!"